version: '3'
services:
  receive-data:
    build:
      context: ./
      dockerfile: Dockerfile.receive
    image: receive-data
    ports:
     - "5000:5000"
    networks:
            app_net:
                ipv4_address: 10.5.0.5
    volumes:
      - ./config/:/usr/src/app/config
      - ./received/:/usr/src/app/received
  send-data:
    build:
      context: ./
      dockerfile: Dockerfile.send
    image: send-data
    depends_on:
      - receive-data
    volumes:
      - ./config/:/usr/src/app/config
      - ./input/:/usr/src/app/input
      - ./xmls/:/usr/src/app/xmls
      - ./sent/:/usr/src/app/sent
    networks:
            app_net:
                ipv4_address: 10.5.0.10
networks:
    app_net:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16