FROM python:2
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/received
RUN mkdir -p /usr/src/app/config
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./config/receive_config.json ./config/receive_config.json
COPY receive_app.py ./
CMD [ "python", "./receive_app.py" ]